### ISSUE TITLE
New release to ROS distro (0.1.2 or later)?

### ISSUE THREAD

**Issue by 130s** [cbandera/rosparam_handler#38]
Since [the last release 0.1.1 done in May 2017](https://github.com/cbandera/rosparam_handler/commit/2a71b336763d4c25ea343d579c11824943301ba8), there are many updates.

Thanks!

**Comment by artivis** [comment]
Hi, thanks for the interest.  
First of all please notice that the project just got a new maintainer (myself) as @cbandera is now quite busy.  
There have been many updates and yet more to come (e.g. #36 & #37). I would like to get those two PR through before releasing a new version (maybe 1.0.0).

**Comment by artivis** [comment]
Hi,
unlike what I've said in my previous message, I'm now planning on releasing the current state of the `develop` branch (at c650412bec3599fd26c5cad02d1f9896b99ca61f).  
It is preferable to do a release considering all changes that were made since 0.1.1 (Unit testing, Python support etc...), and the further refactoring brought by #36 & #37.  

The release of version 0.1.2 is thus pending on #42.

**Comment by artivis** [comment]
Release 0.1.2 is pending due to a `bloom-release` issue ...  
See this post [answers.ros.org](https://answers.ros.org/question/282400/bloom-release-fails-because-the-working-directory-has-changes/).

**Comment by artivis** [comment]
The release process went through yesterday ! In a few days the package should be in the main repo.  
Follow its status [here](http://repositories.ros.org/status_page/ros_indigo_default.html?q=rosparam_handler).
